name: dartson
version: 0.1.6
author: Eric Schneller <eric@schnellers.name>
description: Dartson is a Dart library that can be used to convert Dart objects into a JSON string. It uses dart:mirrors reflection to rebuild the schema. It also works in dart2js when using the dartson builder.
homepage: https://github.com/eredo/dartson
environment:
  sdk: '>=1.3.0'
dependencies:
  analyzer: any
  barback: any
  source_maps: 0.9.3
dev_dependencies:
  unittest: any
